## Note this Docker-Compose file is for local dev environment.
## Read the Readme File for more info.

version: "3.8"
services:
  frontend:
    build:
      context: ./presentation-frontend/presentation-frontend
      dockerfile: Dockerfile
    command: npm run start
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysqldb

  api_server:
    build: ./blogapiservice/blogapiservice
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb

  auth_server:
    build: ./AuthServerService
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: springversion
      MYSQL_USER: tompa
      MYSQL_PASSWORD: 123456tg
      MYSQL_ROOT_PASSWORD: 123456tg
